apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vote-tomcat-hpa
  namespace: vote
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vote-tomcat
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # 평균 CPU 사용률이 60% 넘으면 스케일업
