apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vote-nginx-allow-internal
  namespace: vote
spec:
  podSelector:
    matchLabels:
      app: vote-nginx  # 이 Pod에만 적용
  policyTypes:
  - Ingress
  # 클러스터 외부에서 들어오는 요청 허용
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0  # 모든 외부 IP 허용
  - from:
    # kube-system 네임스페이스 전체 허용
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-system

